name: CD
on:
  push:
    branches: ["main", "dev"]
    paths-ignore:
      - '**.md'

permissions: 
  contents: read
  packages: write

concurrency: 
  group: front-deploy-${{ github.ref_name }}
  cancel-in-progress: false

jobs:
  build-and-deploy:
    runs-on: ubuntu-22.04
    timeout-minutes: 10
    environment:
      name: ${{ github.ref_name == 'main' && 'prod' || 'dev' }}
      url: ${{ steps.set-server-url.outputs.server-url }}
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Lowercase Repository Owner
        run: |
          echo "OWNER_LC=${OWNER,,}" >> ${GITHUB_ENV}
        env:
          OWNER: '${{ github.repository_owner }}'
        
      - name: Set Server Url
        id: set-server-url
        run: |
          echo "server_url=${{ vars.FRONT_SERVER_URL }}" >> $GITHUB_OUTPUT
          
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
